[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = "type"
toolbarMode = "minimal"
showSidebarNavigation = true

[runner]
magicEnabled = true
fastReruns = true
enforceSerializableSessionState = false
enumCoercion = "nameOnly"

[server]
fileWatcherType = "auto"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableStaticServing = false
disconnectedSessionTTL = 120
headless = false
showEmailPrompt = true
runOnSave = false
port = 8501
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
gatherUsageStats = true
serverPort = 8501

[theme]
base = "light"
primaryColor = "#b91c1c"
backgroundColor = "#f6f6f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"
baseRadius = "medium"
buttonRadius = "full"

[theme.sidebar]
primaryColor = "#b91c1c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#111827"
